Best exporter support final best evaluation result output
tensorflow/estimator pull request #60
Opened 2021-02-25 05:15 UTC by zuston

### Why
In estimator, we need to print final eval result when using the best exporter.

2021-02-25 05:18 UTC, zuston commented
@rthadur Please check it. Thanks

2021-05-20 14:18 UTC, gbaned commented
@mihaimaruseac  Can you please review this PR ? Thanks!

2021-07-15 15:03 UTC, gbaned commented
@mihaimaruseac Can you please review this PR ? Thanks!

2021-07-15 16:10 UTC, mihaimaruseac commented
I only supported Estimator BUILD system, not code

2021-11-22 12:02 UTC, gbaned commented
@k-w-w Can you please review this PR ? Thanks!

2021-11-29 21:59 UTC, mihaimaruseac requested changes
Can you add a unit test please?

Estimator is in maintenance mode, we should only be accepting new PRs if there is a test that fails without the PR and passes with it.

2022-12-16 13:51 UTC, gbaned commented
Hi @zuston Can you please check @mihaimaruseac's comments and keep us posted? Thank you!

2022-12-29 16:18 UTC, mihaimaruseac commented
Closing stale PR. Note that Estimator is no longer active, currently it's only updated as needed to fully deprecate from TF.

2022-12-29 16:18 UTC, closed without merging