Remove first export in BestExporter to avoid exporting worse model.
tensorflow/estimator pull request #62
Opened 2021-02-25 14:53 UTC by wuxianxingkong

First export mechanism in BestExporter will export worse model when trainig tasks restart.
@tensorflower-gardener This bug is attached with this issue. Please review it and give some suggestions. Thanks.

2021-05-20 14:21 UTC, gbaned commented
@mihaimaruseac  Can you please review this PR ? Thanks!

2021-07-15 15:03 UTC, gbaned commented
@mihaimaruseac Can you please review this PR ? Thanks!

2021-11-22 12:02 UTC, gbaned commented
@k-w-w Can you please review this PR ? Thanks!

2021-11-29 21:58 UTC, mihaimaruseac requested changes
Can you add a unit test please?

Estimator is in maintenance mode, we should only be accepting new PRs if there is a test that fails without the PR and passes with it.

2022-12-16 13:53 UTC, gbaned commented
Hi @wuxianxingkong Can you please check @mihaimaruseac's comments and keep us posted? Thank you!

2022-12-29 16:17 UTC, mihaimaruseac commented
Closing stale PR. Note that Estimator is no longer active, currently it's only updated as needed to fully deprecate from TF.

2022-12-29 16:17 UTC, closed without merging