Remove tf.contrib detail from the document.
tensorflow/estimator pull request #89
Opened 2022-12-20 21:49 UTC by sachinprasadhs

Removed tf.contrib detail from the tf.compat.v1.estimator.tpu.TPUEstimatorSpec document which would create confusion to the community.

2022-12-29 16:16 UTC, mihaimaruseac approved these changes
Approving, but note that Estimator is no longer active, currently it's only updated as needed to fully deprecate from TF.

2023-01-09 23:21 UTC, nfelt approved these changes

2023-05-01 23:49 UTC, mihaimaruseac commented
> Instead of removing the sentence, replacing this with `tf.summary.create_file_writer`?

2023-05-01 23:49 UTC, mihaimaruseac requested changes
Instead of removing the sentence, replacing this with `tf.summary.create_file_writer`?

2023-05-02 14:25 UTC, mihaimaruseac commented on tensorflow_estimator/python/estimator/tpu/tpu_estimator.py
> +  dimension, and so must be >= rank 1.  The `host_call` is useful for writing
```suggestion
  dimension, and so must be >= rank 1. The `host_call` is useful for writing
```

2023-05-02 17:30 UTC, merged